### ISSUE TITLE
 FaceSwapLab - ERROR - Failed to upscale images do not match

### ISSUE THREAD

**Issue by egoegoegoegoego** [glucauze/sd-webui-faceswaplab#27]
I'm always getting this error message when upscaling: " FaceSwapLab - ERROR - Failed to upscale images do not match" and the end result is a blurred image. Everything else works fine, just the upscaling part. What am I missing here?

**Comment by glucauze** [comment]
Could you give me an example config to understand. Where it happens (txt2img, img2img) and in which part of post-processing you select an upscaler (global or in face units)

I am aware of a bug if you select "None" in Post-Processing Upscaler (not Global Post-Processing). It should be fixed in 1.2.1. Just select LDSR or Lanczos to try if it solve something.

**Comment by egoegoegoegoego** [comment]
Hi, just did "check for updates" in extensions and the problem have been fixed on v1.2.0. it seems I was using an outdated version.. or so i think. anyway, its solved now. thank you very much for this awesome extension. looking forward to what you do next. God bless

**Comment by glucauze** [comment]
Just don't be surprise if you get bad results at first with 1.2.0 since i disabled codeformer by default. But it can be re-enabled easely

**Comment by egoegoegoegoego** [comment]
i tweaked around the sd settings faceswaplab think the results are fine if not better
